<?php
// auth/register.php
require_once __DIR__ . '/../functions/helpers.php';
require_once __DIR__ . '/../config/db.php';

if (is_client_logged_in()) {
    header("Location: /RDG/client/book_slot.php");
    exit;
} elseif (is_admin_logged_in()) {
    header("Location: /RDG/admin/dashboard.php");
    exit;
}

$error = '';
$success = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $first_name = trim($_POST['first_name'] ?? '');
    $last_name = trim($_POST['last_name'] ?? '');
    $email = trim($_POST['email'] ?? '');
    $phone = trim($_POST['phone'] ?? '');
    $otp_code = trim($_POST['otp_code'] ?? '');

    $full_name = trim($first_name . ' ' . $last_name);

    if (empty($first_name) || empty($last_name) || empty($email) || empty($phone) || empty($otp_code)) {
        $error = 'Please fill in all mandatory fields.';
    } elseif (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
        $error = 'Please enter a valid email address.';
    } elseif (!preg_match('/^09\d{9}$/', $phone)) {
        $error = 'Phone number must follow strict PH format (11 digits starting with 09).';
    } else {
        // Verify OTP from session
        $sess_otp = $_SESSION['reg_otp'] ?? '';
        $sess_email = $_SESSION['reg_otp_email'] ?? '';
        $sess_time = $_SESSION['reg_otp_time'] ?? 0;

        if (empty($sess_otp) || empty($sess_email)) {
            $error = 'Please request an OTP verification code first.';
        } elseif (strtolower($email) !== strtolower($sess_email)) {
            $error = 'The registered email does not match the email used to request the OTP.';
        } elseif ($otp_code !== (string)$sess_otp) {
            $error = 'Invalid OTP code. Please check your email and try again.';
        } elseif ((time() - $sess_time) > 600) {
            $error = 'The OTP code has expired (valid for 10 minutes). Please request a new one.';
        } else {
            // Check if email already exists
            $stmt = $pdo->prepare("SELECT id FROM users WHERE email = ? LIMIT 1");
            $stmt->execute([$email]);
            if ($stmt->fetch()) {
                $error = 'An account with this email address already exists.';
            } else {
                // Check if phone number already exists
                $stmt_ph = $pdo->prepare("SELECT id FROM users WHERE phone = ? LIMIT 1");
                $stmt_ph->execute([$phone]);
                if ($stmt_ph->fetch()) {
                    $error = 'An account with this phone number already exists.';
                } else {
                    // Generate secure temporary password
                    $temp_password = "RDG-" . mt_rand(100000, 999999);
                    $password_hash = password_hash($temp_password, PASSWORD_BCRYPT);
                    
                    try {
                        $stmt = $pdo->prepare("
                            INSERT INTO users (email, password_hash, full_name, phone, role, email_verified, is_temp_password) 
                            VALUES (?, ?, ?, ?, 'client', 1, 1)
                        ");
                        $stmt->execute([$email, $password_hash, $full_name, $phone]);
                        $user_id = $pdo->lastInsertId();

                        // Generate welcome notification
                        create_notification(
                            $pdo, 
                            $user_id, 
                            null, 
                            null, 
                            'booking_confirmed', 
                            "Welcome to RDG Tennis, " . htmlspecialchars($full_name) . "! Your athlete account has been successfully created. Your temporary login password is: " . $temp_password
                        );

                        // Clear OTP from session
                        unset($_SESSION['reg_otp']);
                        unset($_SESSION['reg_otp_email']);
                        unset($_SESSION['reg_otp_time']);

                        // Email the user their temporary password
                        $email_body = '
                        <h2>Welcome to RDG Tennis!</h2>
                        <p>Hi ' . htmlspecialchars($full_name) . ',</p>
                        <p>Excellent news! Your athlete profile has been successfully registered and your email verified.</p>
                        
                        <div style="background-color: #bcf0ae; border: 2px solid #154212; padding: 20px; margin: 25px 0; color: #002201; font-weight: bold; border-radius: 0px;">
                            ✓ Email Verified & Profile Created Successfully!
                        </div>

                        <p>To access the player portal, log in using the temporary secure password generated by the system:</p>

                        <table class="details-table" style="width: 100%; border-collapse: collapse; margin: 25px 0; border: 2px solid #154212;">
                            <tr>
                                <th style="background-color: #f0eded; padding: 12px; font-weight: bold; text-transform: uppercase; font-size: 11px; border: 1px solid #154212; color: #154212; text-align: left; width: 35%;">Login Email</th>
                                <td style="padding: 12px; border: 1px solid #154212; font-size: 14px; color: #42493e;">' . htmlspecialchars($email) . '</td>
                            </tr>
                            <tr>
                                <th style="background-color: #f0eded; padding: 12px; font-weight: bold; text-transform: uppercase; font-size: 11px; border: 1px solid #154212; color: #154212; text-align: left;">Temporary Password</th>
                                <td style="padding: 12px; border: 1px solid #154212; font-size: 14px; font-family: monospace; font-weight: bold; color: #154212;">' . htmlspecialchars($temp_password) . '</td>
                            </tr>
                        </table>

                        <p style="background-color: #ffdad6; border: 2px solid #ba1a1a; padding: 15px; font-size: 12px; color: #ba1a1a; font-weight: bold; margin: 25px 0;">
                            ⚠ Security Warning: For security purposes, please login using this temporary password and update your password immediately in your account settings.
                        </p>

                        <p style="text-align: center; margin-top: 30px;">
                            <a href="http://localhost/RDG/auth/login.php" style="display: inline-block; background-color: #FFE500; color: #154212; text-decoration: none; padding: 15px 30px; font-weight: 900; text-transform: uppercase; border: 2px solid #154212; box-shadow: 4px 4px 0px #154212; font-size: 13px; text-align: center;">Log In to Athlete Portal</a>
                        </p>';
                        
                        send_html_email($email, "Welcome to RDG Tennis! Your Temporary Access Credentials", $email_body);

                        // Set success flags for the UI instruction modal
                        $registration_success = true;
                        $success_email = $email;
                        $success_temp_password = $temp_password;

                    } catch (PDOException $e) {
                        $error = 'Registration failed: ' . $e->getMessage();
                    }
                }
            }
        }
    }
}
?>
<!DOCTYPE html>
<html class="light" lang="en">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>RDG Tennis - Athlete Registration</title>
<script src="https://cdn.tailwindcss.com?plugins=forms,container-queries"></script>
<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700;900&family=Lexend:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>
<link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"/>
<script id="tailwind-config">
    tailwind.config = {
        theme: {
            extend: {
                colors: {
                    primary: "#154212",
                    accent: "#FFB800",
                    background: "#fcf9f8",
                    "on-background": "#1c1b1b"
                },
                borderRadius: {
                    DEFAULT: "0px"
                }
            }
        }
    }
</script>
<style>
    body {
        background-image: linear-gradient(#e5e7eb 1px, transparent 1px), linear-gradient(90deg, #e5e7eb 1px, transparent 1px);
        background-size: 64px 64px;
        font-family: 'Lexend', sans-serif;
    }
    .headline {
        font-family: 'Space Grotesk', sans-serif;
    }
</style>
</head>
<body class="bg-background text-on-background min-h-screen flex items-center justify-center p-6">
    <?php if (isset($registration_success) && $registration_success): ?>
        <!-- Success Modal Overlay -->
        <div id="success-reg-modal" class="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4">
            <div class="bg-white border-4 border-primary max-w-md w-full p-6 shadow-[8px_8px_0px_rgba(21,66,18,1)] text-center flex flex-col space-y-6 items-center">
                <span class="material-symbols-outlined text-6xl text-[#FFB800]" style="font-variation-settings: 'FILL' 1;">check_circle</span>
                <div>
                    <h3 class="headline text-xl uppercase text-primary tracking-tight font-black">Profile Registered!</h3>
                    <p class="text-xs text-zinc-600 mt-2 px-2 leading-relaxed font-bold">
                        Excellent! Your athlete profile has been created successfully. A secure temporary login password has been sent to your email:
                        <br><strong class="text-primary font-black underline"><?= htmlspecialchars($success_email) ?></strong>
                    </p>
                </div>
                <div class="bg-[#fcf9f8] border-2 border-primary p-4 w-full text-left space-y-2">
                    <p class="text-[10px] font-bold uppercase text-primary">Instructions:</p>
                    <ul class="text-[10px] text-zinc-600 list-disc list-inside space-y-1 font-bold">
                        <li>Log in using the temporary password.</li>
                        <li>You will be required to change your password immediately upon login.</li>
                    </ul>
                </div>
                <a href="login.php" class="w-full py-4 bg-primary text-white border-2 border-primary headline uppercase tracking-widest font-black text-center hover:bg-[#FFB800] hover:text-primary transition-all duration-200 shadow-[4px_4px_0px_rgba(21,66,18,0.2)] hover:shadow-none">
                    Go to Login Page &rarr;
                </a>
            </div>
        </div>
    <?php endif; ?>
    <div class="w-full max-w-md bg-white border-4 border-primary shadow-[8px_8px_0px_rgba(21,66,18,1)] overflow-hidden">
        
        <!-- Header -->
        <div class="bg-primary text-white p-6 text-center border-b-4 border-primary flex flex-col items-center">
            <img alt="RDG Tennis Logo" class="h-16 w-auto object-contain mb-3" src="/RDG/RDG Logo.jpg"/>
            <h1 class="headline text-2xl font-black tracking-tighter uppercase text-accent">Create Athlete Account</h1>
            <p class="text-xs uppercase tracking-widest text-[#a1d494] mt-1">Access Premium Training Facilities</p>
        </div>

        <!-- Error Notification -->
        <?php if (!empty($error)): ?>
            <div class="bg-red-50 border-b-4 border-red-500 text-red-700 p-4 font-bold text-xs uppercase flex items-center gap-3 animate-pulse">
                <span class="material-symbols-outlined text-red-500 font-bold">error</span>
                <span><?= htmlspecialchars($error) ?></span>
            </div>
        <?php endif; ?>

        <!-- Form -->
        <form method="POST" action="register.php" class="p-6 space-y-4">
            
            <div class="grid grid-cols-2 gap-4">
                <div>
                    <label class="block headline font-bold uppercase text-xs tracking-wider mb-2 text-primary">First Name *</label>
                    <div class="relative">
                        <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-primary text-lg">person</span>
                        <input type="text" name="first_name" required class="w-full pl-10 pr-4 py-3 border-2 border-primary focus:ring-0 focus:border-accent text-sm" placeholder="e.g. Juan" value="<?= htmlspecialchars($first_name ?? '') ?>"/>
                    </div>
                </div>
                <div>
                    <label class="block headline font-bold uppercase text-xs tracking-wider mb-2 text-primary">Last Name *</label>
                    <div class="relative">
                        <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-primary text-lg">person</span>
                        <input type="text" name="last_name" required class="w-full pl-10 pr-4 py-3 border-2 border-primary focus:ring-0 focus:border-accent text-sm" placeholder="e.g. Cruz" value="<?= htmlspecialchars($last_name ?? '') ?>"/>
                    </div>
                </div>
            </div>

            <div>
                <label class="block headline font-bold uppercase text-xs tracking-wider mb-2 text-primary">Email Address *</label>
                <div class="flex gap-2">
                    <div class="relative flex-1">
                        <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-primary text-lg">mail</span>
                        <input type="email" id="email-field" name="email" required class="w-full pl-10 pr-4 py-3 border-2 border-primary focus:ring-0 focus:border-accent text-sm" placeholder="e.g. player@example.com" value="<?= htmlspecialchars($email ?? '') ?>"/>
                    </div>
                    <button type="button" id="send-otp-btn" onclick="sendVerificationOTP()" class="bg-accent text-primary border-2 border-primary px-4 py-3 headline font-black text-xs uppercase hover:bg-primary hover:text-white transition-all shadow-[2px_2px_0px_rgba(21,66,18,1)] active:shadow-none">
                        Send OTP
                    </button>
                </div>
                <p id="otp-status-msg" class="text-[10px] mt-1.5 font-bold uppercase hidden"></p>
            </div>

            <div>
                <label class="block headline font-bold uppercase text-xs tracking-wider mb-2 text-primary">Contact Number *</label>
                <div class="relative">
                    <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-primary text-lg">call</span>
                    <input type="text" id="phone-field" name="phone" required maxlength="11" oninput="this.value = this.value.replace(/[^0-9]/g, '')" class="w-full pl-10 pr-4 py-3 border-2 border-primary focus:ring-0 focus:border-accent text-sm" placeholder="e.g. 09171234567" value="<?= htmlspecialchars($phone ?? '') ?>"/>
                </div>
                <p class="text-[9px] text-[#42493e] font-bold uppercase mt-1">Strict numbers only (PH format: 11 digits starting with 09)</p>
            </div>

            <div>
                <label class="block headline font-bold uppercase text-xs tracking-wider mb-2 text-primary">OTP Verify Email *</label>
                <div class="relative">
                    <span class="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-primary text-lg">domain_verification</span>
                    <input type="text" name="otp_code" required maxlength="6" oninput="this.value = this.value.replace(/[^0-9]/g, '')" class="w-full pl-10 pr-4 py-3 border-2 border-primary focus:ring-0 focus:border-accent text-sm tracking-widest text-center font-bold text-lg" placeholder="123456"/>
                </div>
                <p class="text-[9px] text-[#42493e] font-bold uppercase mt-1">Enter the 6-digit verification code sent to your email</p>
            </div>

            <button type="submit" class="w-full bg-primary text-white border-2 border-primary py-4 headline uppercase tracking-widest font-black flex items-center justify-center gap-3 hover:bg-accent hover:text-primary transition-all duration-200 shadow-[4px_4px_0px_rgba(21,66,18,0.2)] hover:shadow-none">
                Register & Verify <span class="material-symbols-outlined text-lg">how_to_reg</span>
            </button>
        </form>

        <!-- Login Link -->
        <div class="p-6 bg-zinc-50 border-t-2 border-primary text-center text-xs">
            <span class="text-zinc-600">Already registered?</span> 
            <a href="login.php" class="font-bold text-primary underline hover:text-accent ml-1 uppercase">Athlete Login &rarr;</a>
        </div>
    </div>

<script>
function sendVerificationOTP() {
    const emailField = document.getElementById('email-field');
    const firstNameField = document.querySelector('input[name="first_name"]');
    const lastNameField = document.querySelector('input[name="last_name"]');
    const phoneField = document.getElementById('phone-field');
    const sendBtn = document.getElementById('send-otp-btn');
    const statusMsg = document.getElementById('otp-status-msg');

    const email = emailField.value.trim();
    const firstName = firstNameField.value.trim();
    const lastName = lastNameField.value.trim();
    const phone = phoneField.value.trim();

    if (!firstName) {
        alert('Please fill in your First Name before requesting an OTP.');
        firstNameField.focus();
        return;
    }

    if (!lastName) {
        alert('Please fill in your Last Name before requesting an OTP.');
        lastNameField.focus();
        return;
    }

    const fullName = firstName + ' ' + lastName;

    if (!email) {
        alert('Please fill in your Email Address before requesting an OTP.');
        emailField.focus();
        return;
    }

    if (!phone) {
        alert('Please fill in your Contact Number before requesting an OTP.');
        phoneField.focus();
        return;
    }

    if (!/^09\d{9}$/.test(phone)) {
        alert('Contact number must be a strict PH mobile format (11 digits starting with 09).');
        phoneField.focus();
        return;
    }

    // Disable button and show loading state
    sendBtn.disabled = true;
    const originalText = sendBtn.innerHTML;
    sendBtn.innerHTML = 'Sending...';
    
    statusMsg.classList.remove('hidden', 'text-red-600', 'text-green-600');
    statusMsg.classList.add('text-primary');
    statusMsg.textContent = 'Checking details and generating OTP...';
    statusMsg.style.display = 'block';

    const fd = new FormData();
    fd.append('email', email);
    fd.append('full_name', fullName);
    fd.append('phone', phone);

    fetch('../actions/send_otp.php', {
        method: 'POST',
        body: fd
    })
    .then(res => res.json())
    .then(data => {
        sendBtn.disabled = false;
        sendBtn.innerHTML = originalText;

        if (data.success) {
            statusMsg.classList.remove('text-primary', 'text-red-600');
            statusMsg.classList.add('text-green-600');
            statusMsg.textContent = data.message;
            // Focus on OTP input
            document.querySelector('input[name="otp_code"]').focus();
        } else {
            statusMsg.classList.remove('text-primary', 'text-green-600');
            statusMsg.classList.add('text-red-600');
            statusMsg.textContent = data.message;
        }
    })
    .catch(() => {
        sendBtn.disabled = false;
        sendBtn.innerHTML = originalText;
        statusMsg.classList.remove('text-primary', 'text-green-600');
        statusMsg.classList.add('text-red-600');
        statusMsg.textContent = 'Network error. Please try again.';
    });
}
</script>
</body>
</html>
